### PR TITLE
Add --quiet option to output only the rating

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/regebro/pyroma/issues/47.

Demo:

```console
$ pyroma .
------------------------------
Checking .
Found pyroma
------------------------------
Final rating: 10/10
Your cheese is so fresh most people think it's a cream: Mascarpone
------------------------------
$ pyroma . --quiet
10
$
```

### CODE REVIEW

**Review by CAM-Gerlach — COMMENTED** [review]
FWIW, LGTM, assuming @regebro 's fine with the approach ofc. Thanks @hugovk !

**Comment by regebro** [comment]
Could you add a change in the HISTORY.txt as well? Then I can just push merge.

**Comment by hugovk** [comment]
Added!

**Comment by regebro** [comment]
Thanks!

**Pull request merged**
