### PR TITLE
setup.py may be absent

### PR DESCRIPTION
**Pull request by MaxTyulin**
With appearance of PEP517 setup.py file may be missing, in than case pyroma throw an exception, but if the project uses setuptools as build-backend, there is setup.cfg file, than pyroma can use.

### CODE REVIEW

**Comment by regebro** [comment]
Thanks! One question is to handle when you have both setup.py and setup.cfg, which is possible.

**Comment by MaxTyulin** [comment]
It correctly handles the situation when both files exist. Moreover in one project that uses pep517 I create setup.py (which consists only setup() function) only for pyroma and remove it after.

**Comment by regebro** [comment]
OK, cool! Then all that is needed is some test cases for setup.cfg installs.

**Comment by MaxTyulin** [comment]
Done.

**Comment by regebro** [comment]
Great stuff!

**Pull request merged**
