### PR TITLE
Remove Python 2 imports

### PR DESCRIPTION
**Pull request by hugovk**
Followup to https://github.com/regebro/pyroma/pull/52.

And explicitly concatenate some strings post-Black formatting.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
NB, all good changes but FYI it will have a minor conflict with PR #58 , which does a few of the same import changes, so up to @regebro which to merge first.

**Comment by hugovk** [comment]
Thanks for the pointer!

#58 is more important, I suggest merging that first then ping me to fix any conflicts :)

**Comment by regebro** [comment]
@hugovk OK, #58 is merged!

**Comment by hugovk** [comment]
Thanks, rebased!

**Pull request merged**
