### PR TITLE
Enforce black and flake8

### PR DESCRIPTION
**Pull request by regebro**
No idea why I don't have this on all my packages already

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Instead of manually adding and configuring it here, which results in duplicate config and will be out of sync with the versions you have pinned `pre-commit-ci.yaml`, wouldn't it be simpler, more maintainable and more reliable to just add the pre-commit action to run your existing pre-commit checks?

This also runs all the checks in parallel so you see the results of all of them, not just whichever happened to fail first. Likewise, it would also be a good idea to throw this in a separate job rather than conflating it with the package tests, so it both finishes faster and doesn't block the tests running and vice versa.

I can submit a PR if you want, just lmk.

**Comment by CAM-Gerlach** [comment]
> Likewise, it would also be a good idea to throw this in a separate job rather than conflating it with the package tests, so it both finishes faster and doesn't block the tests running and vice versa.

Great example of this in action — on #83 , all the "test" jobs error out immediately due to Black formatting nits, so I can't see any actual test output.

Also, running it with the tests means it has to run on every Python version and platform in the matrix, whereas due to the design of these static analysis tools, it only needs to run on one, as it would as a separate job.

**Comment by regebro** [comment]
> just add the pre-commit action to run your existing pre-commit checks (i.e. black and flake8)?

Yes, that's a very good idea.

**Comment by CAM-Gerlach** [comment]
Thanks, opened as #85

**Pull request merged**
